name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to ECR and Docker Hub
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and tag Docker image
        run: |
          rev=$(git rev-parse --short HEAD)
          docker build -t hello .
          docker tag hello 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mama-repo
          docker tag hello $DOCKER_USERNAME/mama-repo:${rev}

      - name: Push to ECR
        run: |
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com
          docker push 244530008913.dkr.ecr.eu-west-1.amazonaws.com/mama-repo

      - name: Push to Docker Hub
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          rev=$(git rev-parse --short HEAD)
          docker push $DOCKER_USERNAME/mama-repo:${rev}
        env:
          DOCKER_CLI_ACI_OFF: "1"
          DOCKER_BUILDKIT: "0"


